### ISSUE TITLE
Denison listed as NA

### ISSUE THREAD

**Issue by samclifford** [MilesMcBain/tidy_aus_ssm#1]
The 2017 redistribution has seen [Denison renamed as Clark](http://www.aec.gov.au/profiles/tas/clark.htm) as of 14 November 2017 but the reported values from the ABS are based on the 2016 boundaries. You may want to find a new source of electoral information or just renamed Clark as Denison.

**Comment by MilesMcBain** [comment]
Amazing. Thanks Sam.

**Comment by MilesMcBain** [comment]
Okay so the state is robust to redistributions now. :)
